spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/watsapp

spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

jwt.secret=change-this-secret-key-minimum-32-characters-long
jwt.expiration=86400000

# Write application logs to a project file.
logging.file.name=logs/chat-microservice.log

# Include custom controller/service/filter debug logs.
logging.level.com.watsappclone.start=DEBUG
